language: python

python:
  - "3.7"
  - "3.8"
  - "3.9"

install:
  - pip install -r requirements.txt

script:
  - pytest

services:
  - postgresql

arch: amd64 
os: linux
dist: focal
virt: lxd

deploy:
  provider: pypi
  username: "__token__"
  skip_existing: true
  password:
    secure: AHEObvGhk2kB3DVCbTGWGP9+KeKY615H3586gyMCeFF4CfHHA/0twXPgugn+BJxF7r3bNNsLquN/q1WnuXTMermTLtSVnfKkIMPb7T+WfTgAgDsQqYkEEqA/1Ic5rmmRaNV2EG3VtbAiSAyp9ozAg2XDJOU9kmWBO10Mb7/JkI7HdK85MExTmvh/Hf8vK4uS3ecjIqYWRbx3G4as/Xs0TSxzjKhx4DY6nWLpLoEzLn8uPY+n2U22Z7x97znWS9qmo1yjUiP1LRAeHjsUQi9auwG6kils9/TcNl42OonjuEhB7z8gYvg4ICh2fgbSM7AahCLC1JOqkpVDXIbFhs//o84Ry3PNYputIAx+thDQO95iNY+5QMjT60XpyMNe+nPTvCphJuOz21lU6WKb2XI94uP+5mXaC0k0I2nNXlgfIKjhNtAFoHEr2oikje0zTe0D7YFfIqhYkSTKWwG01R/AHvxiKIXtVU0D4ymLxqqNSrtIJakcKCBACRhZh9t9MD2OPgm5ANVLBHgN9kuC5TfuKkJfs7JEspuDDGtltBUYOFUiQ9kujN6GbXBLsp+o2LhQ/DX85jF+j1loKQugLuK8oipo3UbPA+Pr7v47Pvd6yl5/AShly+JEfyj1J4q9kEVY5RGg/0lL4ueY+aMcstme7RQQdow5gV8uqR6+KPL06JQ=
  on:
    tags: true
